trigger:
  branches:
    include:
      - develop

pool:
  name: 'Default'

variables:
  - group: SonarQube

steps:
  - script: |
      dotnet tool install --global dotnet-sonarscanner
      dotnet tool install --global dotnet-coverage
    displayName: 'Install tools'

  - script: |
      dotnet sonarscanner begin /k:"zootech-backend" /n:"ZooTech Backend" /d:sonar.token="$(SONAR_TOKEN)" /d:sonar.host.url="$(SONAR_HOST_URL)" /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml"
    displayName: 'SonarQube Begin'

  - script: |
      dotnet build "ZooTech Backend - Solution.slnx" --no-incremental --disable-build-servers
    displayName: 'Build'

  - script: |
      dotnet-coverage collect "dotnet test ""ZooTech Backend - Solution.slnx"" --no-build" -f xml -o "coverage.xml"
    displayName: 'Test & Coverage'

  - script: |
      dotnet sonarscanner end /d:sonar.token="$(SONAR_TOKEN)"
    displayName: 'SonarQube End'