namespace ZooTech.InterfaceAdapters.Modules.Module_Vacuno.DTOs.ReporteVacuno.Responses;

public sealed record RegistroVacunoReporteResponseDto(
    RegistroVacunoDetalleDto Vacuno,
    IReadOnlyCollection<object> Historial,
    string? DownloadUrl);

public sealed record RegistroVacunoDetalleDto(
    long Id,
    string Codigo,
    string Nombre,
    DateOnly FechaNacimiento,
    string? AdquisicionPor,
    decimal? PrecioCompra,
    string? Raza,
    string? Color,
    string? Sexo,
    string? CodigoPadre,
    string? CodigoMadre,
    string? CodigoAbuelo,
    string? CodigoAbuela,
    string? Granja,
    string? Distrito,
    string? Departamento,
    string? Provincia,
    string? Procedencia,
    string? AptoPara,
    DateOnly? FechaEspecificacion,
    string? Observaciones,
    string? FotoUrl,
    string? Estado,
    DateOnly FechaRegistro,
    DateTime CreadoEn,
    DateTime ActualizadoEn,
    long? FotoId,
    string? FotoNombreOriginal,
    string? FotoNombreAlmacenado,
    string? FotoRuta,
    string? FotoExtension,
    long? FotoTamanoBytes,
    string? EstadoActualCode,
    string? EstadoActualNombre,
    DateOnly? FechaEstado,
    string? MotivoEstado,
    DateOnly? FechaAdquisicion,
    string? CreadoPor,
    string? ActualizadoPor);

