// <auto-generated />
#pragma warning disable CS8618

namespace ZooTech.Domain.Configuration;

public static class Features
{
    public static readonly FeatureCode ModuleVacunos = new("MODULE_VACUNOS");
    public static readonly FeatureCode ModuleVacunosReportes = new("MODULE_VACUNOS_REPORTES");
    public static readonly FeatureCode ModuleVacunosReproduccion = new("MODULE_VACUNOS_REPRODUCCION");
}
