// <auto-generated />
#pragma warning disable CS8618

namespace ZooTech.Domain.Configuration;

public static class Rules
{
    public static readonly RuleCode VacunosEliminacionCondicionada = new("VACUNOS_ELIMINACION_CONDICIONADA");
    public static readonly RuleCode VacunosFecundacionPendienteUnica = new("VACUNOS_FECUNDACION_PENDIENTE_UNICA");
    public static readonly RuleCode VacunosFecundacionTrazabilidad = new("VACUNOS_FECUNDACION_TRAZABILIDAD");
}
