// <auto-generated />
#pragma warning disable CS8618

namespace ZooTech.Domain.Configuration;

public static class Settings
{
    public static class Vacunos
    {
        public static readonly SettingDefinition<int> VacunosArbolMaxNiveles = new("VACUNOS_ARBOL_MAX_NIVELES");
        public static readonly SettingDefinition<int> VacunosArbolMinNiveles = new("VACUNOS_ARBOL_MIN_NIVELES");
        public static readonly SettingDefinition<int> VacunosCodigoMaxLength = new("VACUNOS_CODIGO_MAX_LENGTH");
        public static readonly SettingDefinition<bool> VacunosCodigoUppercaseRequired = new("VACUNOS_CODIGO_UPPERCASE_REQUIRED");
        public static readonly SettingDefinition<int> VacunosDefaultFilterDays = new("VACUNOS_DEFAULT_FILTER_DAYS");
        public static readonly SettingDefinition<int> VacunosEliminacionUndoSeconds = new("VACUNOS_ELIMINACION_UNDO_SECONDS");
        public static readonly SettingDefinition<int> VacunosFecundacionObservacionesMaxLength = new("VACUNOS_FECUNDACION_OBSERVACIONES_MAX_LENGTH");
        public static readonly SettingDefinition<string> VacunosFotoFormatosPermitidos = new("VACUNOS_FOTO_FORMATOS_PERMITIDOS");
        public static readonly SettingDefinition<int> VacunosInputMaxLength = new("VACUNOS_INPUT_MAX_LENGTH");
        public static readonly SettingDefinition<int> VacunosObservacionesMaxLength = new("VACUNOS_OBSERVACIONES_MAX_LENGTH");
        public static readonly SettingDefinition<int> VacunosObservacionesMaxWords = new("VACUNOS_OBSERVACIONES_MAX_WORDS");
        public static readonly SettingDefinition<string> VacunosReporteFormatosDescarga = new("VACUNOS_REPORTE_FORMATOS_DESCARGA");
    }
}
