using System.Text;
using ZooTech.CodeGeneration.Models;

namespace ZooTech.CodeGeneration.Generators;

public sealed class FeaturesGenerator
{
    public string Generate(IReadOnlyCollection<FeatureMetadata> features)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#pragma warning disable CS8618");
        sb.AppendLine();
        sb.AppendLine("namespace ZooTech.Domain.Configuration;");
        sb.AppendLine();
        sb.AppendLine("public static class Features");
        sb.AppendLine("{");

        foreach (var feature in features)
        {
            sb.AppendLine(
                $"""
                    public static readonly FeatureCode {ToPascal(feature.Code)} = new("{feature.Code}");
                """);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ToPascal(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return value;

        var parts = value
            .ToLower()
            .Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);

        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            sb.Append(char.ToUpper(part[0]));
            if (part.Length > 1)
                sb.Append(part.Substring(1));
        }

        var result = sb.ToString();

        if (result.Length > 0 && char.IsDigit(result[0]))
            result = "_" + result;

        return result;
    }
}
