using System.Text;

namespace ZooTech.CodeGeneration.Generators;

/// <summary>
/// Shared helpers for the code generators. Extracted to eliminate duplication between
/// <see cref="FeaturesGenerator"/> and <see cref="RulesGenerator"/> (and partially
/// <see cref="SettingsGenerator"/>), without changing any generated output.
/// </summary>
internal static class GeneratorSupport
{
    /// <summary>
    /// Generates a static class containing one strongly-typed code constant per item,
    /// e.g. <c>public static readonly FeatureCode Foo = new("FOO");</c>.
    /// </summary>
    public static string GenerateCodeDefinitions<T>(
        IReadOnlyCollection<T> items,
        string wrapperClassName,
        string targetTypeName,
        Func<T, string> codeSelector)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#pragma warning disable CS8618");
        sb.AppendLine();
        sb.AppendLine("namespace ZooTech.Domain.Configuration;");
        sb.AppendLine();
        sb.AppendLine($"public static class {wrapperClassName}");
        sb.AppendLine("{");

        foreach (var item in items)
        {
            var code = codeSelector(item);
            sb.AppendLine(
                $"""
                    public static readonly {targetTypeName} {ToPascal(code)} = new("{code}");
                """);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string ToPascal(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return value;

        var parts = value
            .ToLower()
            .Split(new[] { '_', '-', ' ' }, StringSplitOptions.RemoveEmptyEntries);

        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            sb.Append(char.ToUpper(part[0]));
            if (part.Length > 1)
                sb.Append(part.Substring(1));
        }

        var result = sb.ToString();

        if (result.Length > 0 && char.IsDigit(result[0]))
            result = "_" + result;

        return result;
    }
}
