using System.Text;
using ZooTech.CodeGeneration.Models;

namespace ZooTech.CodeGeneration.Generators;

public sealed class SettingsGenerator
{
    public string Generate(IReadOnlyCollection<SettingMetadata> settings)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#pragma warning disable CS8618");
        sb.AppendLine();
        sb.AppendLine("namespace ZooTech.Domain.Configuration;");
        sb.AppendLine();
        sb.AppendLine("public static class Settings");
        sb.AppendLine("{");

        foreach (var group in settings.GroupBy(x => x.GroupCode))
        {
            sb.AppendLine($"    public static class {GeneratorSupport.ToPascal(group.Key)}");
            sb.AppendLine("    {");

            foreach (var item in group)
            {
                sb.AppendLine(
                    $"""
                            public static readonly SettingDefinition<{MapType(item.DataType)}> {GeneratorSupport.ToPascal(item.Code)} = new("{item.Code}");
                    """);
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string MapType(string dataType)
    {
        if (string.IsNullOrWhiteSpace(dataType))
            return "string";

        return dataType.ToUpper() switch
        {
            "INT" or "INTEGER" => "int",
            "DECIMAL" or "NUMERIC" or "MONEY" => "decimal",
            "BOOL" or "BOOLEAN" or "BIT" => "bool",
            "DATE" => "DateOnly",
            "DATETIME" => "DateTime",
            "JSON" or "ARRAY" => "string",
            _ => "string"
        };
    }
}
