namespace ZooTech.Application.Modules.Module_Vacuno.UseCases.ReporteVacuno.ObtenerRegistroVacunoReporte;

public sealed record RegistroVacunoReporteResponse(
    RegistroVacunoDetalle Vacuno,
    IReadOnlyCollection<object> Historial,
    string? DownloadUrl);

public sealed record RegistroVacunoDetalle(
    long Id,
    string Codigo,
    string Nombre,
    DateOnly FechaNacimiento,
    string? AdquisicionPor,
    decimal? PrecioCompra,
    string? Raza,
    string? Color,
    string? Sexo,
    string? CodigoPadre,
    string? CodigoMadre,
    string? CodigoAbuelo,
    string? CodigoAbuela,
    string? Granja,
    string? Distrito,
    string? Departamento,
    string? Provincia,
    string? Procedencia,
    string? AptoPara,
    DateOnly? FechaEspecificacion,
    string? Observaciones,
    long? FotoId,
    string? FotoNombreOriginal,
    string? FotoNombreAlmacenado,
    string? FotoRuta,
    string? FotoUrl,
    string? FotoExtension,
    long? FotoTamanoBytes,
    string? EstadoActualCode,
    string? EstadoActualNombre,
    string? Estado,
    DateOnly? FechaEstado,
    string? MotivoEstado,
    DateOnly FechaRegistro,
    int DiasRegistrado,
    DateOnly? FechaAdquisicion,
    string? CreadoPor,
    DateTime CreadoEn,
    string? ActualizadoPor,
    DateTime ActualizadoEn);
