using Microsoft.Extensions.Configuration;
using ZooTech.CodeGeneration.Generators;
using ZooTech.CodeGeneration.Readers;
using ZooTech.CodeGeneration.Writers;

namespace ZooTech.CodeGeneration.IntegrationTests;

public sealed class CodeGenerationPipelineTests
{
    private static readonly string SolutionRoot = Path.GetFullPath(
        Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", ".."));

    private static readonly string DomainConfigDir = Path.GetFullPath(
        Path.Combine(SolutionRoot, "src", "ZooTech.Domain", "Configuration"));

    [Fact]
    public async Task RunPipeline_WithInvalidConnectionString_GeneratesEmptyStubs()
    {
        var reader = new MetadataReader("Server=invalid;Database=invalid;Trusted_Connection=True;");
        var writer = new FileWriter();

        IReadOnlyCollection<ZooTech.CodeGeneration.Models.SettingMetadata> settings;
        IReadOnlyCollection<ZooTech.CodeGeneration.Models.FeatureMetadata> features;
        IReadOnlyCollection<ZooTech.CodeGeneration.Models.RuleMetadata> rules;

        try
        {
            settings = await reader.GetSettingsAsync();
            features = await reader.GetFeaturesAsync();
            rules = await reader.GetRulesAsync();
        }
        catch
        {
            settings = Array.Empty<ZooTech.CodeGeneration.Models.SettingMetadata>();
            features = Array.Empty<ZooTech.CodeGeneration.Models.FeatureMetadata>();
            rules = Array.Empty<ZooTech.CodeGeneration.Models.RuleMetadata>();
        }

        var settingsPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString(), "Settings.g.cs");
        var featuresPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString(), "Features.g.cs");
        var rulesPath = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString(), "Rules.g.cs");

        writer.Write(settingsPath, new SettingsGenerator().Generate(settings));
        writer.Write(featuresPath, new FeaturesGenerator().Generate(features));
        writer.Write(rulesPath, new RulesGenerator().Generate(rules));

        Assert.True(File.Exists(settingsPath));
        Assert.True(File.Exists(featuresPath));
        Assert.True(File.Exists(rulesPath));

        var settingsContent = File.ReadAllText(settingsPath);
        Assert.Contains("public static class Settings", settingsContent);

        var featuresContent = File.ReadAllText(featuresPath);
        Assert.Contains("public static class Features", featuresContent);

        var rulesContent = File.ReadAllText(rulesPath);
        Assert.Contains("public static class Rules", rulesContent);

        // Cleanup
        File.Delete(settingsPath);
        File.Delete(featuresPath);
        File.Delete(rulesPath);
    }

    [Fact]
    public void GeneratedFiles_CompileAsPartOfDomain()
    {
        var settingsFile = Path.Combine(DomainConfigDir, "Settings.g.cs");
        var featuresFile = Path.Combine(DomainConfigDir, "Features.g.cs");
        var rulesFile = Path.Combine(DomainConfigDir, "Rules.g.cs");

        Assert.True(File.Exists(settingsFile), $"Missing: {settingsFile}");
        Assert.True(File.Exists(featuresFile), $"Missing: {featuresFile}");
        Assert.True(File.Exists(rulesFile), $"Missing: {rulesFile}");

        var settingsContent = File.ReadAllText(settingsFile);
        Assert.Contains("<auto-generated />", settingsContent);
        Assert.Contains("namespace ZooTech.Domain.Configuration", settingsContent);

        var featuresContent = File.ReadAllText(featuresFile);
        Assert.Contains("<auto-generated />", featuresContent);
        Assert.Contains("namespace ZooTech.Domain.Configuration", featuresContent);

        var rulesContent = File.ReadAllText(rulesFile);
        Assert.Contains("<auto-generated />", rulesContent);
        Assert.Contains("namespace ZooTech.Domain.Configuration", rulesContent);
    }

    [Fact]
    public void GeneratedSettings_HaveActualData_WhenDbIsAvailable()
    {
        var settingsFile = Path.Combine(DomainConfigDir, "Settings.g.cs");
        var content = File.ReadAllText(settingsFile);

        var hasVacunosGroup = content.Contains("public static class Vacunos");
        var hasSettingsDefs = content.Contains("SettingDefinition<");

        if (hasVacunosGroup && hasSettingsDefs)
        {
            Assert.Contains("VacunosDefaultFilterDays", content);
            Assert.Contains("SettingDefinition<int>", content);
        }
    }
}
