<Project Sdk="Microsoft.NET.Sdk">


  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="QuestPDF" Version="2026.7.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.13.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZooTech.Application\ZooTech.Application.csproj" />
    <ProjectReference Include="..\ZooTech.Domain\ZooTech.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\Entities\GanaderiaDb\" />
    <Folder Include="Persistence\Entities\MainTenantsDb\" />
    <Folder Include="Persistence\Mappers\" />
    <Folder Include="Persistence\Repositories\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>

